[tool.poetry]
name = "day1"
version = "0.1.0"
description = "learning fastapi"
authors = ["sharyar khan"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.1"
uvicorn = "^0.29.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
